# Generated by Django 5.2.1 on 2025-06-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("free_time", models.CharField(blank=True, max_length=100)),
                ("personal_info", models.TextField(blank=True)),
                ("wx_qrcode", models.CharField(blank=True, max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("agent", "探员"), ("admin", "管理员")],
                        default="agent",
                        max_length=10,
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("updated_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
